// theme.config.js
export const metadata = {
  title: "Blog next auth",
  description: "Generated by create next app",
  image: "", // URL gambar untuk digunakan ketika dibagikan di media sosial
  url: "https://fajarr.space", // URL halaman web Anda
};

export const config = [
  {
    type: "navbar",
    title: "About",
    url: "/",
  },
  {
    type: "navbar",
    title: "Photos",
    url: "/photos",
  },
  {
    type: "navbar",
    title: "Posts",
    url: "/posts",
  },
  {
    type: "footer",
    name: "©  stuff-blog",
    year: new Date().getFullYear(),
  },
  {
    type: "footer",
    social: "GitHub",
    url: "https://github.com/fajarspace",
  },
];
