import Head from "next/head";
import { Inter } from "next/font/google";
import { ThemeProvider } from "next-themes";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const meta = {
  title: "Blog next auth",
  description: "Generated by create next app",
  image: "", // URL gambar untuk digunakan ketika dibagikan di media sosial
  url: "https://fajarr.space", // URL halaman web Anda
};

export default function RootLayout({ children }) {
  return (
    <>
      <Head>
        <meta name="robots" content="follow, index" />
        <meta name="description" content={meta.description} />
        <meta property="og:site_name" content={meta.title} />
        <meta property="og:description" content={meta.description} />
        <meta property="og:title" content={meta.title} />
        <meta property="og:image" content={meta.image} />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:site" content="@yourname" />
        <meta name="twitter:title" content={meta.title} />
        <meta name="twitter:description" content={meta.description} />
        <meta name="twitter:image" content={meta.image} />
      </Head>
      <ThemeProvider>
        <div className={inter.className}>
          <article className="container prose md:prose">
            <Navbar />
            {children}
            <Footer />
          </article>
        </div>
      </ThemeProvider>
    </>
  );
}
